version: '3.8'

services:
  # 1. Database MongoDB
  mongodb:
    image: mongo:latest
    container_name: flashsale_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Redis (Cache & Inventory)
  redis:
    image: redis:alpine
    container_name: flashsale_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # 3. RabbitMQ (Message Queue)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: flashsale_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Port để code connect
      - "15672:15672" # Port để vào web quản lý (User/Pass mặc định: guest/guest)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data: